export type EditVariants =
  | "profile"
  | "add-experience"
  | "work-experience"
  | "projects"
  | "add-projects"
  | "licenses"
  | "add-licenses"
  | "education"
  | "add-education"
  | "awards"
  | "add-awards"
  | "resume"
  | "basic-information"
  | "add-basic-information"
