import QueryProvider from "@/lib/providers/QueryProvider"
import UserProvider from "@store/user-provider"
import type { Metadata } from "next"
import { Baloo_2 } from "next/font/google"
import "./globals.css"

const baloo = Baloo_2({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Bezt",
  description: "Generated by Bezt",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={baloo.className}>
        <QueryProvider>
          <UserProvider>{children}</UserProvider>
        </QueryProvider>
      </body>
    </html>
  )
}
