version: '3.6'
services:
  db:
    image: postgres:14
    restart: always
    container_name: bezt_pwa_dev_db
    environment:
      POSTGRES_DB: ${DOCKER_POSTGRES_DB}
      POSTGRES_PASSWORD: ''
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '${DOCKER_POSTGRES_DB_PORT}:5432'
    volumes:
      - bezt_dev_db_data:/var/lib/postgresql/data
    networks:
      - bezt_dev_db_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-d', '${DOCKER_POSTGRES_DB}']
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
networks:
  bezt_dev_db_network:
volumes:
  bezt_dev_db_data:
