export const data = [
  {
    streak: 1,
    rewardName: 'Any 3 Power-Ups',
    quantity: 3,
    rewardType: 'POWER_UPS',
  },
  {
    streak: 2,
    rewardName: '1 day SteakShield',
    quantity: 1,
    rewardType: 'STREAK_SHIELD',
  },
  {
    streak: 3,
    rewardName: 'League-in Pass 1',
    quantity: 1,
    rewardType: 'LEAGUE_IN_PASS',
  },
  {
    streak: 5,
    rewardName: 'Earn 1x Virt. Coins',
    quantity: 1,
    rewardType: 'VIRTUAL_COINS',
  },
  {
    streak: 7,
    rewardName: 'Any 5 Power-Ups',
    quantity: 5,
    rewardType: 'POWER_UPS',
  },
  {
    streak: 9,
    rewardName: '2 day StreakShield',
    quantity: 2,
    rewardType: 'STREAK_SHIELD',
  },
  {
    streak: 12,
    rewardName: 'League-Up Pass 2',
    quantity: 2,
    rewardType: 'LEAGUE_UP_PASS',
  },
  {
    streak: 2,
    rewardName: 'Any 3 Power-Ups',
    quantity: 3,
    rewardType: 'POWER_UPS',
  },
  {
    streak: 15,
    rewardName: 'StreakBadge 15',
    quantity: 15,
    rewardType: 'STREAK_BADGE',
  },
  {
    streak: 18,
    rewardName: 'Earn 2x Virt. Coins',
    quantity: 2,
    rewardType: 'VIRTUAL_COINS',
  },
  {
    streak: 22,
    rewardName: 'Any 6 Power-Ups',
    quantity: 6,
    rewardType: 'POWER_UPS',
  },
  {
    streak: 26,
    rewardName: '3 day StreakShield',
    quantity: 3,
    rewardType: 'STREAK_SHIELD',
  },
  {
    streak: 30,
    rewardName: 'League-Up Pass 3',
    quantity: 3,
    rewardType: 'LEAGUE_UP_PASS',
  },
  {
    streak: 35,
    rewardName: 'Earn 4x Virt. Coins',
    quantity: 4,
    rewardType: 'VIRTUAL_COINS',
  },
  {
    streak: 40,
    rewardName: 'Any 7 Power-Ups',
    quantity: 7,
    rewardType: 'POWER_UPS',
  },
  {
    streak: 45,
    rewardName: '4 day StreakShield',
    quantity: 4,
    rewardType: 'STREAK_SHIELD',
  },
  {
    streak: 51,
    rewardName: 'StreakBadge 50+',
    quantity: 50,
    rewardType: 'STREAK_BADGE',
  },
  {
    streak: 57,
    rewardName: 'League-Up Pass 4',
    quantity: 4,
    rewardType: 'LEAGUE_UP_PASS',
  },
  {
    streak: 63,
    rewardName: 'Earn 6x Virt. Coins',
    quantity: 6,
    rewardType: 'VIRTUAL_COINS',
  },
  {
    streak: 70,
    rewardName: 'Any 8 Power-Ups',
    quantity: 8,
    rewardType: 'POWER_UPS',
  },
  {
    streak: 77,
    rewardName: '5 day StreakShield',
    quantity: 5,
    rewardType: 'STREAK_SHIELD',
  },
  {
    streak: 84,
    rewardName: 'League-Up Pass 5',
    quantity: 5,
    rewardType: 'LEAGUE_UP_PASS',
  },
  {
    streak: 92,
    rewardName: 'Earn 9x Virt. Coins',
    quantity: 3,
    rewardType: 'POWER_UPS',
  },
  {
    streak: 100,
    reward: 'StreakBadge 100',
    quantity: 100,
    rewardType: 'STREAK_BADGE',
  },
  {
    streak: 108,
    reward: 'Any 9 Power-Ups',
    quantity: 9,
    rewardType: 'POWER_UPS',
  },
  {
    streak: 117,
    reward: '6 day StreakShield',
    quantity: 6,
    rewardType: 'STREAK_SHIELD',
  },
  {
    streak: 126,
    reward: 'League-Up Pass 6',
    quantity: 6,
    rewardType: 'LEAGUE_UP_PASS',
  },
  {
    streak: 135,
    reward: 'Earn 12x Virt. Coins',
    quantity: 12,
    rewardType: 'VIRTUAL_COINS',
  },
  {
    streak: 145,
    reward: 'Any 10 Power-Ups',
    quantity: 10,
    rewardType: 'POWER_UPS',
  },
  {
    streak: 155,
    reward: 'StreakBadge 150+',
    quantity: 150,
    rewardType: 'STREAK_BADGE',
  },
  {
    streak: 165,
    reward: '7 day StreakShield',
    quantity: 7,
    rewardType: 'STREAK_SHIELD',
  },
  {
    streak: 180,
    reward: 'League-Up Pass 7',
    quantity: 7,
    rewardType: 'LEAGUE_UP_PASS',
  },
  {
    streak: 195,
    reward: 'Earn 16x Virt. Coins',
    quantity: 16,
    rewardType: 'VIRTUAL_COINS',
  },
  {
    streak: 210,
    reward: 'StreakBadge 200+',
    quantity: 200,
    rewardType: 'STREAK_BADGE',
  },
  {
    streak: 225,
    reward: 'League-Up Pass 8',
    quantity: 8,
    rewardType: 'LEAGUE_UP_PASS',
  },
  {
    streak: 245,
    reward: 'Earn 20x Virt. Coins',
    quantity: 20,
    rewardType: 'VIRTUAL_COINS',
  },
  {
    streak: 265,
    reward: 'StreakBadge 250+',
    quantity: 250,
    rewardType: 'STREAK_BADGE',
  },
  {
    streak: 285,
    reward: 'Earn 25x Virt. Coins',
    quantity: 25,
    rewardType: 'VIRTUAL_COINS',
  },
  {
    streak: 310,
    reward: 'StreakBadge 300+',
    quantity: 300,
    rewardType: 'STREAK_BADGE',
  },
  {
    streak: 335,
    reward: 'Earn 30x Virt. Coins',
    quantity: 30,
    rewardType: 'VIRTUAL_COINS',
  },
  {
    streak: 365,
    reward: 'StreakBadge 365',
    quantity: 365,
    rewardType: 'STREAK_BADGE',
  },
];
