import type { Metadata } from "next"
import Header from "./components/header"
import MyRank from "./components/my-rank"

export const metadata: Metadata = {
  title: "Rankings",
  description: "Generated by Bezt",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div className="bg-alice-blue w-[380px] no-scrollbar h-screen mx-auto relative z-1">
      <Header />
      <div>{children}</div>
      <MyRank />
    </div>
  )
}
